apiVersion: v1
kind: Pod
metadata:
  name: kafka-client-python
  labels:
    app: kafka-clients
spec:
  containers:
    - name: kafka-client-python
      image: python:3.10-slim
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - name: sample-scripts
          mountPath: /sample_scripts
  volumes:
  - name: sample-scripts
    hostPath:
      path: /Users/manojmukkamala/Documents/GitHub/vysh_temp/kubernetes/kafka_clients/sample_scripts