global:
 scrape_interval: 10s
 evaluation_interval: 10s
scrape_configs:
 - job_name: 'kafka'
   static_configs:
    - targets:
      - kafka-broker:7071
 - job_name: 'spark-application'
   static_configs:
    - targets:
        - jupyterlab:4040   
   metrics_path: /metrics/prometheus
 - job_name: 'spark-master'
   static_configs:
    - targets:
      - spark-master:8080
   metrics_path: /metrics/master/prometheus        
 - job_name: 'spark-worker-1'
   static_configs:
    - targets:
      - spark-worker-1:8081
   metrics_path: /metrics/prometheus  
 - job_name: 'spark-worker-2'
   static_configs:
    - targets:
      - spark-worker-2:8081 
   metrics_path: /metrics/prometheus