apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-thrift-server
  labels:
    app: spark-cluster
spec:
  serviceName: spark-thrift-server
  replicas: 1
  selector:
    matchLabels:
      app: spark-cluster
      node: spark-thrift-server
  template:
    metadata:
      labels:
        app: spark-cluster
        node: spark-thrift-server
    spec:
      containers:
        - name: spark-thrift-server
          image: kub_spark_image:latest
          imagePullPolicy: Never
          env:
            - name: SPARK_WORKLOAD
              value: "thrift"
          volumeMounts:
            - name: odp-intra-storage
              mountPath: /opt/spark/work-dir/odp_intra_storage           
      volumes:
        - name: odp-intra-storage
          hostPath:
            path: /Users/manojmukkamala/kube_volumes/odp_intra_storage              
---
apiVersion: v1
kind: Service
metadata:
  name: spark-thrift-server 
  labels:
    app: spark-cluster   
spec:
  type: NodePort
  selector:
    app: spark-cluster
    node: spark-thrift-server
  ports:
    - targetPort: 10000
      port: 10000
      nodePort: 30300    
      name: spark-thrift-server
    - targetPort: 10001
      port: 10001
      nodePort: 30301    
      name: spark-thrift-server-http