version: "3.6"
volumes:
  shared-workspace:
    name: "shared-workspace"
    driver: local
services:
  jupyterlab:
    image: spark_image
    container_name: jupyterlab
    environment:
      - SPARK_WORKLOAD=jupyter     
    ports:
      - 8888:8888
      - 4041:4040
    volumes:
      - /Users/manojmukkamala/Documents/GitHub/manoj_repo/:/opt/spark/work-dir/manoj_repo
      - shared-workspace:/opt/spark/shared-workspace
  spark-master:
    image: spark_image
    container_name: spark-master
    environment:
      - SPARK_WORKLOAD=master
    ports:
      - 8080:8080
      - 7077:7077
      - 4040:4040
    volumes:
      - /Users/manojmukkamala/Documents/GitHub/manoj_repo/:/opt/spark/work-dir/manoj_repo
      - shared-workspace:/opt/spark/shared-workspace
  spark-worker-1:
    image: spark_image
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
      - SPARK_WORKLOAD=worker      
    ports:
      - 8081:8081
    volumes:
      - /Users/manojmukkamala/Documents/GitHub/manoj_repo/:/opt/spark/work-dir/manoj_repo
      - shared-workspace:/opt/spark/shared-workspace
    depends_on:
      - spark-master
  spark-worker-2:
    image: spark_image
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
      - SPARK_WORKLOAD=worker      
    ports:
      - 8082:8081
    volumes:
      - /Users/manojmukkamala/Documents/GitHub/manoj_repo/:/opt/spark/work-dir/manoj_repo
      - shared-workspace:/opt/spark/shared-workspace
    depends_on:
      - spark-master      
  spark-history-server:
    image: spark_image
    container_name: spark-history-server
    environment:
      - SPARK_WORKLOAD=history      
    ports:
      - 18080:18080
    volumes:
      - /Users/manojmukkamala/Documents/GitHub/manoj_repo/:/opt/spark/work-dir/manoj_repo
      - shared-workspace:/opt/spark/shared-workspace 
    depends_on:
      - spark-master