apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
  labels:
    app: kafka-cluster
spec:
  serviceName: kafka-broker
  replicas: 3
  selector:
    matchLabels:
      app: kafka-cluster
      node: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-cluster
        node: kafka-broker
    spec:
      containers:
      - name: kafka-broker
        image: kub_kafka_image:latest
        imagePullPolicy: Never
        env:
          - name: KAFKA_WORKLOAD
            value: "broker"        
          - name: ZOOKEEPER_HOST
            value: zookeeper
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name              
        ports:
        - containerPort: 9092
        volumeMounts:
          - name: kafka-logs
            mountPath: /tmp
            subPathExpr: $(POD_NAME)
      volumes:
        - name: kafka-logs
          hostPath:
            path: /Users/manojmukkamala/kube_volumes/odp_intra_storage/kafka/kafka-broker/tmp
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  labels:
    app: kafka-cluster
spec:
  clusterIP: None
  selector:
    app: kafka-cluster
    node: kafka-broker
  ports:
    - targetPort: 9092
      port: 9092
      name: kafka-broker-listener
    - targetPort: 7071
      port: 7071
      name: kafka-broker-metrics 