apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
spec:
  type: NodePort
  selector:
    app: kafka-ui
  ports:
    - targetPort: 8080
      port: 8080
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-deployment
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          imagePullPolicy: Never
          env:
          - name: KAFKA_CLUSTERS_0_NAME
            value: "kafka-broker-statefulset-0"     
          - name: KAFKA_CLUSTERS_1_NAME
            value: "kafka-broker-statefulset-1"
          - name: KAFKA_CLUSTERS_2_NAME
            value: "kafka-broker-statefulset-2"            
          - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
            value: "kafka-broker-statefulset-0.kafka-broker-service.open-data-platform.svc.cluster.local:9092"  
          - name: KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS
            value: "kafka-broker-statefulset-1.kafka-broker-service.open-data-platform.svc.cluster.local:9092"
          - name: KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS
            value: "kafka-broker-statefulset-2.kafka-broker-service.open-data-platform.svc.cluster.local:9092"                                                    
          ports:
          - containerPort: 8080