apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-ui
  labels:
    app: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-cluster
      node: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-cluster
        node: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          imagePullPolicy: Never
          env:
          - name: KAFKA_CLUSTERS_0_NAME
            value: "kafka-broker-0"     
          - name: KAFKA_CLUSTERS_1_NAME
            value: "kafka-broker-1"
          - name: KAFKA_CLUSTERS_2_NAME
            value: "kafka-broker-2"            
          - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
            value: "kafka-broker-0.kafka-broker.open-data-platform.svc.cluster.local:9092"  
          - name: KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS
            value: "kafka-broker-1.kafka-broker.open-data-platform.svc.cluster.local:9092"
          - name: KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS
            value: "kafka-broker-2.kafka-broker.open-data-platform.svc.cluster.local:9092"                                                    
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
spec:
  type: NodePort
  selector:
    app: kafka-cluster
    node: kafka-ui
  ports:
    - targetPort: 8080
      port: 9090
      nodePort: 30090         