apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1-service
spec:
  type: ClusterIP
  selector:
    app: kafka-broker-1
  ports:
    - targetPort: 9092
      port: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-1
  template:
    metadata:
      labels:
        app: kafka-broker-1
    spec:
      containers:
      - name: kafka-broker-1
        image: kub_kafka_image:latest
        imagePullPolicy: Never
        env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_WORKLOAD
            value: "broker"            
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-broker-1-service:9092"           
          - name: ZOOKEEPER_HOST
            value: zookeeper-service       
        ports:
        - containerPort: 9092
          name: kafka-broker-1
---          
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-2-service
spec:
  type: ClusterIP
  selector:
    app: kafka-broker-2
  ports:
    - targetPort: 9092
      port: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-2
  template:
    metadata:
      labels:
        app: kafka-broker-2
    spec:
      containers:
      - name: kafka-broker-2
        image: kub_kafka_image:latest
        imagePullPolicy: Never
        env:
          - name: KAFKA_BROKER_ID
            value: "2"
          - name: KAFKA_WORKLOAD
            value: "broker"    
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-broker-2-service:9092"                    
          - name: ZOOKEEPER_HOST
            value: zookeeper-service       
        ports:
        - containerPort: 9092
          name: kafka-broker-2         