apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: kafka-cluster
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: kafka-cluster
      node: zookeeper
  template:
    metadata:
      labels:
        app: kafka-cluster
        node: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: kub_kafka_image:latest
          imagePullPolicy: Never
          env:
          - name: KAFKA_WORKLOAD
            value: "zookeeper"          
          ports:
          - containerPort: 2181
          volumeMounts:
            - name: zookeeper-logs
              mountPath: /tmp/zookeeper       
      volumes:
        - name: zookeeper-logs
          hostPath:
            path: /Users/manojmukkamala/kube_volumes/odp_intra_storage/kafka/zookeeper/tmp/zookeeper          
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: kafka-cluster  
spec:
  clusterIP: None
  selector:
    app: kafka-cluster
    node: zookeeper
  ports:
    - targetPort: 2181
      port: 2181