apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - targetPort: 2181
      port: 2181
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: kub_kafka_image:latest
          imagePullPolicy: Never
          env:
          - name: KAFKA_WORKLOAD
            value: "zookeeper"          
          ports:
          - containerPort: 2181