version: "3.6"
services:
  zookeeper:
    image: ubuntu/zookeeper:edge
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - odp_intra_network
  kafka-broker:
    image: ubuntu/kafka:edge
    container_name: kafka-broker
    environment:
      - ZOOKEEPER_HOST=zookeeper
    ports:
      - 9092:9092
    networks:
      - odp_intra_network      
    depends_on:
      - zookeeper    
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    networks:
      - odp_intra_network      
    depends_on:
      - kafka-broker
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-broker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:9092    

networks:
  odp_intra_network:
    external: true